spring:
  datasource:
    url: jdbc:mysql://localhost:3306/examplesdb?useSSL=false&serverTimezone=Asia/Seoul
    username: ustory
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql   # 추가
    database-platform: org.hibernate.dialect.MySQL8Dialect # 추가

    hibernate:
      ddl-auto: create  # 스키마 자동 생성
    show-sql: true      # SQL 쿼리 출력